/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package practicatallerordenamiento;

import java.math.BigDecimal;
import java.math.RoundingMode;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Augusto
 */
public class Vista extends javax.swing.JFrame {

    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    Alumnado alumnos;
    Cafeteria algOrd = new Cafeteria();
    int cantAlumnos;
    int contador = 0;
    DefaultTableModel modelo;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoModoLlenado = new javax.swing.ButtonGroup();
        grupoMetodoOrdenamiento = new javax.swing.ButtonGroup();
        btnGuardarAlumnos = new javax.swing.JButton();
        tbxCantidadAlumnos = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        rbtLlenadoManual = new javax.swing.JRadioButton();
        rbtLlenadoAutomatico = new javax.swing.JRadioButton();
        panelGuardadoManual = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tbxPromedio = new javax.swing.JTextField();
        tbxDocumento = new javax.swing.JTextField();
        btnGuardarAlumno = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        panelMetodosOrdenamiento = new javax.swing.JPanel();
        rbtMetodoBurbuja = new javax.swing.JRadioButton();
        rbtMetodoIntercambio = new javax.swing.JRadioButton();
        rbtMetodoQuicksort = new javax.swing.JRadioButton();
        rbtMetodoSeleccion = new javax.swing.JRadioButton();
        btnOrdenar = new javax.swing.JButton();
        btnReiniciar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnGuardarAlumnos.setText("GUARDAR DATOS");
        btnGuardarAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarAlumnosActionPerformed(evt);
            }
        });

        jLabel1.setText("Cantidad de Alumnos");

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Documento", "Promedio", "Tiquetes"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabla);
        if (tabla.getColumnModel().getColumnCount() > 0) {
            tabla.getColumnModel().getColumn(0).setResizable(false);
            tabla.getColumnModel().getColumn(1).setResizable(false);
            tabla.getColumnModel().getColumn(2).setResizable(false);
        }

        grupoModoLlenado.add(rbtLlenadoManual);
        rbtLlenadoManual.setText("LLENAR MANUAL");

        grupoModoLlenado.add(rbtLlenadoAutomatico);
        rbtLlenadoAutomatico.setText("PROBAR PROGRAMA");

        jLabel3.setText("Promedio");
        jLabel3.setEnabled(false);

        tbxPromedio.setEnabled(false);

        tbxDocumento.setEnabled(false);

        btnGuardarAlumno.setText("Guardar alumno");
        btnGuardarAlumno.setEnabled(false);
        btnGuardarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarAlumnoActionPerformed(evt);
            }
        });

        jLabel2.setText("Documento");
        jLabel2.setEnabled(false);

        javax.swing.GroupLayout panelGuardadoManualLayout = new javax.swing.GroupLayout(panelGuardadoManual);
        panelGuardadoManual.setLayout(panelGuardadoManualLayout);
        panelGuardadoManualLayout.setHorizontalGroup(
            panelGuardadoManualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGuardadoManualLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGuardadoManualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnGuardarAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbxDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbxPromedio, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addContainerGap())
        );
        panelGuardadoManualLayout.setVerticalGroup(
            panelGuardadoManualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGuardadoManualLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tbxDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tbxPromedio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnGuardarAlumno)
                .addContainerGap())
        );

        grupoMetodoOrdenamiento.add(rbtMetodoBurbuja);
        rbtMetodoBurbuja.setText("BURBUJA");
        rbtMetodoBurbuja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtMetodoBurbujaActionPerformed(evt);
            }
        });

        grupoMetodoOrdenamiento.add(rbtMetodoIntercambio);
        rbtMetodoIntercambio.setText("INTERCAMBIO");
        rbtMetodoIntercambio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtMetodoIntercambioActionPerformed(evt);
            }
        });

        grupoMetodoOrdenamiento.add(rbtMetodoQuicksort);
        rbtMetodoQuicksort.setText("QUICKSORT");
        rbtMetodoQuicksort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtMetodoQuicksortActionPerformed(evt);
            }
        });

        grupoMetodoOrdenamiento.add(rbtMetodoSeleccion);
        rbtMetodoSeleccion.setText("SELECCION");
        rbtMetodoSeleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtMetodoSeleccionActionPerformed(evt);
            }
        });

        btnOrdenar.setText("ORDENAR");
        btnOrdenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMetodosOrdenamientoLayout = new javax.swing.GroupLayout(panelMetodosOrdenamiento);
        panelMetodosOrdenamiento.setLayout(panelMetodosOrdenamientoLayout);
        panelMetodosOrdenamientoLayout.setHorizontalGroup(
            panelMetodosOrdenamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMetodosOrdenamientoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMetodosOrdenamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtMetodoBurbuja)
                    .addComponent(rbtMetodoSeleccion)
                    .addComponent(rbtMetodoIntercambio)
                    .addComponent(rbtMetodoQuicksort)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMetodosOrdenamientoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnOrdenar)
                        .addGap(16, 16, 16)))
                .addContainerGap())
        );
        panelMetodosOrdenamientoLayout.setVerticalGroup(
            panelMetodosOrdenamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMetodosOrdenamientoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbtMetodoBurbuja)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtMetodoSeleccion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtMetodoIntercambio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtMetodoQuicksort, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOrdenar)
                .addContainerGap())
        );

        rbtMetodoQuicksort.setActionCommand("QUICKSORT");

        panelMetodosOrdenamiento.setVisible(false);

        btnReiniciar.setText("REINICIAR");
        btnReiniciar.setEnabled(false);
        btnReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReiniciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(rbtLlenadoManual)
                                .addComponent(rbtLlenadoAutomatico))
                            .addComponent(tbxCantidadAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGuardarAlumnos))
                        .addGap(107, 107, 107)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelGuardadoManual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(panelMetodosOrdenamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(btnReiniciar)))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(panelGuardadoManual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbtLlenadoManual)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtLlenadoAutomatico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addGap(4, 4, 4)
                        .addComponent(tbxCantidadAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGuardarAlumnos))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(panelMetodosOrdenamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(btnReiniciar)
                .addGap(72, 72, 72))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarAlumnosActionPerformed
        cantAlumnos = Integer.parseInt(tbxCantidadAlumnos.getText());
        alumnos = new Alumnado(cantAlumnos);
        if(rbtLlenadoManual.isSelected()) {
            cambiarPanelIngreso(true);
        }
        else {
            for (int i = 0; i<alumnos.getCantAlumnos();i++) {
                alumnos.setDocumento(i, Generador.generarDocumento());
                alumnos.setPromedio(i, Generador.generarPromedio());
                panelMetodosOrdenamiento.setVisible(true);
            }
            guardarAlumnos();
            mostrarTabla();
        }
        btnGuardarAlumnos.setEnabled(false);
    }//GEN-LAST:event_btnGuardarAlumnosActionPerformed

    private void cambiarPanelIngreso(boolean estado) {
        for (int i = 0; i < panelGuardadoManual.getComponentCount(); i++) {
            panelGuardadoManual.getComponent(i).setEnabled(estado);
        }
    }

    private void btnGuardarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarAlumnoActionPerformed
       try {
           final float promedio = Float.parseFloat(tbxPromedio.getText());
            if (contador < cantAlumnos && (promedio <= 5 && promedio >= 3)) {
                alumnos.setDocumento(contador, tbxDocumento.getText());
                alumnos.setPromedio(contador, new BigDecimal(promedio).setScale(2, RoundingMode.HALF_UP));
                contador++;
            }
            else {
                throw new Exception();
            }
       } catch(Exception e) {
           JOptionPane.showMessageDialog(null, "REVISE LOS DATOS INTRODUCIDOS E INTENTE NUEVAMENTE", "ERROR", 0);
       }
       
       if (contador == cantAlumnos) {
           cambiarPanelIngreso(false);
            guardarAlumnos();
            mostrarTabla();
            panelMetodosOrdenamiento.setVisible(true);
       }
       
        tbxDocumento.setText("");
        tbxPromedio.setText("");
    }//GEN-LAST:event_btnGuardarAlumnoActionPerformed

    private void guardarAlumnos() {
        alumnos.calcularNroTiquetes();
        algOrd.setAlumn(alumnos);
        alumnos = null;
    }
    
    private void mostrarTabla() {
        modelo = new DefaultTableModel();
        modelo.setColumnIdentifiers(new String[] {"Documento", "Promedio", "Tiquetes"});
        for (int i = 0; i < algOrd.getAlumn().getCantAlumnos(); i++) {
            modelo.addRow(new Object[] {algOrd.getAlumn().getDocumento(i), String.format("%.1f", algOrd.getAlumn().getPromedio(i)), algOrd.getAlumn().getNroTiquetes(i)});
        }
        tabla.setModel(modelo);
    }

    private void rbtMetodoSeleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtMetodoSeleccionActionPerformed
        rbtMetodoSeleccion.setActionCommand("SELECCION");
    }//GEN-LAST:event_rbtMetodoSeleccionActionPerformed

    private void btnOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenarActionPerformed
        String seleccion = grupoMetodoOrdenamiento.getSelection().getActionCommand();
        switch(seleccion) {
            
            case "BURBUJA" -> {
                algOrd.ordenarBurbuja();
            }
                
            case "SELECCION" -> {
                algOrd.ordenarSeleccion();
            }
            
            case "INTERCAMBIO" -> {
                algOrd.ordenarIntercambio();
            }
                
            case "QUICKSORT" -> {
                algOrd.ordenarQuickSort(0, algOrd.getAlumn().getCantAlumnos()-1);
            }
        }
        mostrarTabla();
        btnOrdenar.setEnabled(false);
        btnReiniciar.setEnabled(true);
    }//GEN-LAST:event_btnOrdenarActionPerformed

    private void rbtMetodoBurbujaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtMetodoBurbujaActionPerformed
        rbtMetodoBurbuja.setActionCommand("BURBUJA");
    }//GEN-LAST:event_rbtMetodoBurbujaActionPerformed

    private void rbtMetodoIntercambioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtMetodoIntercambioActionPerformed
        rbtMetodoIntercambio.setActionCommand("INTERCAMBIO");
    }//GEN-LAST:event_rbtMetodoIntercambioActionPerformed

    private void rbtMetodoQuicksortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtMetodoQuicksortActionPerformed
        rbtMetodoQuicksort.setActionCommand("QUICKSORT");
    }//GEN-LAST:event_rbtMetodoQuicksortActionPerformed

    private void btnReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReiniciarActionPerformed
        this.setVisible(false);
        new Vista().setVisible(true);
    }//GEN-LAST:event_btnReiniciarActionPerformed



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarAlumno;
    private javax.swing.JButton btnGuardarAlumnos;
    private javax.swing.JButton btnOrdenar;
    private javax.swing.JButton btnReiniciar;
    private javax.swing.ButtonGroup grupoMetodoOrdenamiento;
    private javax.swing.ButtonGroup grupoModoLlenado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panelGuardadoManual;
    private javax.swing.JPanel panelMetodosOrdenamiento;
    private javax.swing.JRadioButton rbtLlenadoAutomatico;
    private javax.swing.JRadioButton rbtLlenadoManual;
    private javax.swing.JRadioButton rbtMetodoBurbuja;
    private javax.swing.JRadioButton rbtMetodoIntercambio;
    private javax.swing.JRadioButton rbtMetodoQuicksort;
    private javax.swing.JRadioButton rbtMetodoSeleccion;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField tbxCantidadAlumnos;
    private javax.swing.JTextField tbxDocumento;
    private javax.swing.JTextField tbxPromedio;
    // End of variables declaration//GEN-END:variables
}
